-- Migration: Create document_embeddings table for semantic search
-- Description: Stores vector embeddings generated by Gemini AI for legislative documents

CREATE TABLE IF NOT EXISTS `document_embeddings` (
  `document_id` int(11) NOT NULL,
  `embedding` longtext NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`document_id`),
  CONSTRAINT `fk_document_embeddings_doc` FOREIGN KEY (`document_id`) REFERENCES `legislative_documents` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
